language: node_js

node_js:
- 'node'

install:
- npm install

cache:
  directories:
  - ./node_modules

script:
- npm run lint
- docker run -p 27017:27017 mongo
- npm run test
- sh -x scripts/build.sh $REPO $TRAVIS_COMMIT

before_deploy:
- docker --version
- pip install --user awscli # install aws cli w/o sudo
- export PATH=$PATH:$HOME/.local/bin # put aws in the path

deploy:
- provider: script
  script: sh -x scripts/deploy.sh $REPO $TRAVIS_COMMIT $CLUSTER $SERVICE $AWS_REGION
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
