swagger: '2.0'

info:
  version: '0.0.1'
  title: 'Ansyn-TB API'

basePath: '/v2/api'

consumes:
- application/json
produces:
- application/json

paths:
  /swagger:
    x-swagger-pipe: 'swagger_raw'
  /ansyn/upload:
    $ref: './yamls/ansyn/upload.yaml'
  /ansyn/fetch:
    $ref: './yamls/ansyn/fetch.yaml'
