swagger: "2.0"
info:
  version: "1.0.0"
  title: TB api
host: localhost:10010
basePath: /api
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /ansyn/upload:
    $ref: 'http://localhost:8081/yamls/ansyn/upload.yaml'
